# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalorieCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalorieCheck
pod 'Firebase/Analytics'
pod 'FirebaseFirestore'
pod 'Firebase/Auth'
end
